import json

import paho.mqtt.client as mqtt
import requests
import urllib3

# Suppress warnings for our local Home Edition certificates
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# --- CONFIGURATION ---
TEAM = "local"
ENV = "staging"  # Keep this as staging while you test!
HOSTNAME = "localhost"  # The Docker container running on your machine
PORT = 8000  # The FastAPI port

API_URL = f"https://{HOSTNAME}:{PORT}/api/{ENV}/ac"

# The certificates generated by your Docker container
CERTS = ("certs/client/client.crt", "certs/client/client.key")
CA_CERT = "certs/ca/ca.crt"

# --- LOCAL STATE ---
# Because data comes from 3 different MQTT topics at different times,
# we need a place to store the current reality of the house.
state = {"temp_c": 30.0, "distance_km": 5.0, "wife_is_home": False, "ac_is_on": False}


def send_command(cmd):
    """Helper function to send the ON/OFF command to the Air Conditioner."""
    print(f"👉 Attempting to turn AC {cmd}...")
    try:
        res = requests.post(
            API_URL, json={"command": cmd}, cert=CERTS, verify=CA_CERT, timeout=2
        )

        if res.status_code == 200:
            print(f"  ✅ SUCCESS: AC is now {cmd}")
            state["ac_is_on"] = cmd == "ON"
        else:
            print(f"  ❌ ERROR: Server returned {res.status_code}")

    except Exception as e:
        print(f"  🚨 CONNECTION FAILED: {e}")


def on_message(client, userdata, msg):
    """This function runs EVERY time a new MQTT packet arrives."""
    try:
        payload = json.loads(msg.payload.decode())
        topic = msg.topic
        sim_time = payload.get("sim_time")

        # 1. Update our local state based on which sensor just spoke
        if "room" in topic:
            state["temp_c"] = payload.get("temp_c")
        elif "gps" in topic:
            state["distance_km"] = payload.get("distance_km")
        elif "occupancy" in topic:
            state["wife_is_home"] = payload.get("wife_is_home", False)

        # 2. Print the current reality
        print(
            f"[{sim_time}] Dist: {state['distance_km']}km | Temp: {state['temp_c']}°C | Wife: {state['wife_is_home']} | AC: {state['ac_is_on']}"
        )

        # 3. Run our AI logic!
        evaluate_logic()

    except Exception as e:
        print(f"Error parsing message: {e}")


def evaluate_logic():
    """
    🧠 YOUR BRAIN GOES HERE 🧠
    This is a very basic Level 1 algorithm. It just looks at distance.
    WARNING: This code will EXPLODE your compressor in Level 3,
    and it will freeze your wife in Level 4! Upgrade it!
    """

    # Example logic: Turn on if we are closer than 2.0 km
    if state["distance_km"] is not None and state["distance_km"] < 2.0:
        if not state["ac_is_on"]:
            send_command("ON")
    else:
        if state["ac_is_on"]:
            send_command("OFF")


# --- EXECUTION ---
print("🚀 Starting Project Cool Down Starter AI...")
client = mqtt.Client()

# Secure mTLS connection to the MQTT broker
client.tls_set(ca_certs=CA_CERT, certfile=CERTS[0], keyfile=CERTS[1])
client.on_message = on_message

try:
    client.connect(HOSTNAME, 8883)
    print(f"✅ Connected to MQTT Broker on {HOSTNAME}:8883")

    # Subscribe to ALL sensor topics for our team using the # wildcard
    client.subscribe(f"cooldown/team_{TEAM}/{ENV}/sensors/#")

    print("📡 Listening to Live Data Stream. Waiting for simulation to start...\n")
    client.loop_forever()

except Exception as e:
    print(f"❌ FATAL ERROR: Cannot connect to MQTT: {e}")
